name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - thespbgamer
body:
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The problem is ...
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: 1. Go to '...' 2. Click on '....' 3. Do '....' 4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: It should be doing ...
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the mod are you running?
      placeholder: I'm on the version 2.0.0
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: settings
    attributes:
      label: Settings
      description: If applicable, add your settings of the mod here (if not using defaults, screenshots are fine for this).
    validations:
      required: true